import {createState,getJob,matchJob,generateGreeting,updateProfile,sendGreeting,simulateReply,approveResume,fillForm,validateForm,submitForm,reconcile,syncJobs,counts} from './engine.mjs';
let state=createState();
const ui={view:'jobs',selected:'j1',application:'j4',q:'',source:'全部平台',city:'全部城市'};
const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root');
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escape;
const names={jobs:'岗位工作台',messages:'消息与确认',applications:'官网网申',records:'投递记录',profile:'我的资料'};
const icons={jobs:'▦',messages:'▤',applications:'▧',records:'≡',profile:'○'};
const opt=(values,current)=>values.map(v=>`<option ${v===current?'selected':''}>${e(v)}</option>`).join('');
const logo=j=>`<div class="company-logo ${j.tone}-bg" aria-hidden="true">${e(j.initial)}</div>`;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3600);}
function filteredJobs(){return state.jobs.filter(j=>(ui.source==='全部平台'||j.source===ui.source)&&(ui.city==='全部城市'||j.city===ui.city)&&(!ui.q||`${j.title}${j.company}${j.tags.join('')}`.toLowerCase().includes(ui.q.toLowerCase())));}
function jobCard(j,application=false){const m=matchJob(state,j.id);const selected=application?ui.application===j.id:ui.selected===j.id;return `<button class="job-card ${selected?'selected':''}" data-act="${application?'pick-application':'pick-job'}" data-id="${j.id}" aria-pressed="${selected}">${logo(j)}<div class="job-main"><h3>${e(j.title)}</h3><div class="company-line">${e(j.company)} · ${e(j.city)} · 示例岗位</div><div class="row" style="margin-top:9px"><span class="salary">${e(j.salary)}</span><span class="pill ${m.level}">${e(m.label)}</span></div><div class="chips"><span class="chip">${e(j.source)}</span>${j.tags.slice(0,2).map(t=>`<span class="chip">${e(t)}</span>`).join('')}</div></div></button>`;}
function summaryJob(j){return `<div class="row"><div style="display:flex;align-items:center;gap:12px">${logo(j)}<div><strong>${e(j.company)}</strong><div class="small muted">示例企业 · ${e(j.source)}</div></div><span class="pill neutral">${j.source==='企业官网'?'秋招岗位':'实习岗位'}</span></div><h2>${e(j.title)}</h2><p class="small muted">${e(j.city)} · ${e(j.degree)}${j.days?` · 每周 ${j.days} 天`:''}</p>`;}
function jobDetails(j){const m=matchJob(state,j.id),draft=state.drafts[j.id],sent=state.statuses[j.id]?.greeting;return `<section class="card" aria-label="岗位详情"><div class="detail-head">${summaryJob(j)}</div><div class="detail-part"><div class="eyebrow">岗位要求</div><p>${e(j.summary)}</p><ul>${j.requirements.map(r=>`<li>${e(r)}</li>`).join('')}</ul></div><div class="detail-part"><div class="row"><h3>与你的资料对照</h3><span class="pill ${m.level}">${e(m.label)}</span></div><div class="match-box"><div>可对应的经历：${e(m.hits.join('、')||'暂无直接对应')}</div><div class="evidence">资料原文：${e(state.profile.experience)}</div>${m.gaps.map(x=>`<div class="warning">需确认：${e(x)}</div>`).join('')}</div><div class="draft-hint">依据示例资料和预设规则展示，未调用真实大模型。</div></div>${j.source==='企业官网'?`<div class="detail-part"><h3>到官网申请</h3><p>带入示例资料，检查填写内容后再确认本次申请。</p><div class="actions"><button class="btn primary" data-act="open-application" data-id="${j.id}">体验官网网申 →</button></div></div>`:`<div class="detail-part"><div class="row"><h3>打招呼文案</h3><button class="btn link small" data-act="generate" data-id="${j.id}">${draft?'重新生成':'生成草稿'}</button></div>${draft?`<label class="field-label" for="greeting">检查或修改这次要发送的内容</label><textarea id="greeting" maxlength="500">${e(draft.text)}</textarea><div class="draft-hint">仅使用示例资料中已有的经历，不补写未提供的经验。</div><div class="actions"><button class="btn primary" data-act="review-greeting" data-id="${j.id}" ${sent?'disabled':''}>${sent?'已模拟发送':'检查并模拟发送'}</button>${sent?`<button class="btn" data-act="reply" data-id="${j.id}">模拟 HR 索要简历</button>`:''}</div>`:`<p>根据这份 JD 和你的资料生成草稿，检查后再决定是否发送。</p><div class="actions"><button class="btn primary" data-act="generate" data-id="${j.id}">生成打招呼草稿</button></div>`}</div>`}<div class="detail-footer">此处展示产品交互；招聘平台接入及实际页面操作尚待验证。</div></section>`;}
function jobsView(){let jobs=filteredJobs();if(!jobs.some(j=>j.id===ui.selected)&&jobs.length)ui.selected=jobs[0].id;const c=counts(state);return `<div class="page-head"><div><h1>岗位工作台</h1><p>找到合适的岗位，再决定如何沟通。</p></div><button class="btn" data-act="sync">↻ 同步示例岗位</button></div><div class="stats"><div class="stat"><span class="stat-icon">▦</span><div><strong>${c.jobs}</strong><small>已整理的示例岗位</small></div></div><div class="stat"><span class="stat-icon">▤</span><div><strong>${c.pending}</strong><small>简历请求待确认</small></div></div><div class="stat"><span class="stat-icon">✓</span><div><strong>${c.applications}</strong><small>已模拟完成网申</small></div></div></div><div class="workspace"><section class="card" aria-label="岗位筛选与列表"><form id="filters" class="filters"><label class="search"><span class="field-label">岗位或公司</span><input name="q" value="${e(ui.q)}" placeholder="试试 AI 产品、数据、用户研究"></label><label><span class="field-label">招聘平台</span><select name="source">${opt(['全部平台','BOSS直聘','实习僧','企业官网'],ui.source)}</select></label><label><span class="field-label">工作城市</span><select name="city">${opt(['全部城市','上海','北京','杭州'],ui.city)}</select></label><button class="btn blue" type="submit">筛选岗位</button><button class="btn" type="button" data-act="reset-filters">重置筛选</button></form><div class="list-label"><span>找到 ${jobs.length} 个示例岗位</span><span>点击查看详情</span></div><div class="job-list">${jobs.map(j=>jobCard(j)).join('')||'<div class="empty"><strong>暂无符合条件的岗位</strong>换个关键词，或重置筛选。</div>'}</div></section>${jobs.length?jobDetails(getJob(state,ui.selected)):'<section class="card empty">放宽筛选条件后，岗位详情会显示在这里。</section>'}</div>`;}
function messagesView(){return `<div class="page-head"><div><h1>消息与确认</h1><p>HR 索要简历时，由你确认收件人和文件版本。</p></div><button class="btn" data-act="simulate-message">＋ 添加一条示例请求</button></div><div class="view-grid"><section class="card"><div class="card-pad"><div class="eyebrow">待办说明</div><h2>你的简历，由你决定何时发</h2><p class="muted" style="margin-top:12px">这里的会话均为虚构。取消确认不会发送；完成确认只会更新演示记录。</p><div class="stepper"><div class="step on">01 收到请求</div><div class="step on">02 核对材料</div><div class="step">03 确认发送</div></div><button class="btn light" data-act="view" data-view="profile">查看示例资料</button></div></section><section class="card" aria-label="简历请求">${state.messages.map(m=>{const j=getJob(state,m.jobId);return `<article class="message-row"><div class="row"><div style="display:flex;gap:11px;align-items:center">${logo(j)}<div><strong>${e(j.company)} · 招聘同事</strong><div class="small muted">${e(j.title)}</div></div></div><span class="pill ${m.status==='pending'?'warn':'good'}">${m.status==='pending'?'等待你的确认':'已模拟发送'}</span></div><div class="message-text">${e(m.text)}</div><div class="small muted">识别为：${e(m.intent)} · 示例会话</div><div class="actions"><button class="btn ${m.status==='pending'?'primary':''}" data-act="review-resume" data-id="${m.id}" ${m.status!=='pending'?'disabled':''}>${m.status==='pending'?'核对并发送简历':'本次请求已处理'}</button></div></article>`;}).join('')}</section></div>`;}
function formFields(f){const field=(key,label,type='text',placeholder='')=>`<label><span class="field-label">${label} *</span><input name="${key}" type="${type}" value="${e(f[key])}" ${key==='graduation'?'pattern="20[0-9]{2}" maxlength="4"':''} placeholder="${placeholder}" required></label>`;return `<div class="form-grid">${field('name','姓名')}${field('email','邮箱','email','请填示例邮箱，如 demo@example.com')}${field('school','学校')}${field('major','专业')}${field('graduation','毕业年份')}<label><span class="field-label">简历附件 *</span><input name="resume" value="${e(f.resume)}" required><div class="field-note">只展示文件名称，不上传任何真实文件。</div></label><label class="span-2"><span class="field-label">相关经历 *</span><textarea name="experience" required>${e(f.experience)}</textarea></label></div>`;}
function applicationsView(){const jobs=state.jobs.filter(j=>j.source==='企业官网'),j=getJob(state,ui.application),f=state.forms[j.id],status=state.statuses[j.id]?.application;return `<div class="page-head"><div><h1>官网网申</h1><p>从示例秋招表选择岗位，体验填写、检查和确认。</p></div><span class="pill neutral">${jobs.length} 个示例官网岗位</span></div><div class="view-grid"><section class="card"><div class="card-pad"><div class="eyebrow">秋招岗位更新表</div><h2>选择本次申请</h2><p class="small muted" style="margin-top:8px">示例行已核对。此页不会打开或填写真实企业网站。</p></div>${jobs.map(x=>jobCard(x,true)).join('')}</section><section class="card"><div class="detail-head">${summaryJob(j)}</div><div class="card-pad"><div class="stepper"><div class="step on">01 选择岗位</div><div class="step ${f?'on':''}">02 填写信息</div><div class="step ${status?'on':''}">03 确认提交</div></div>${status?`<div class="callout ${status==='结果待核验'?'':'info'}"><strong>${e(status)}</strong><br>${status==='结果待核验'?'模拟提交后断网，结果暂时不明。先核验申请记录，不重复提交。':'本次申请已记录，重复提交已拦截。'}</div><div class="actions">${status==='结果待核验'?`<button class="btn primary" data-act="reconcile" data-id="${j.id}">核验示例申请记录</button>`:''}<button class="btn" data-act="view" data-view="records">查看投递记录</button></div>`:f?`<div class="callout">示例邮箱尚未提供，请补全后检查本份申请。建议使用虚构信息体验。</div><form id="application-form" data-id="${j.id}">${formFields(f)}<div class="actions"><button class="btn primary" type="submit">检查本份申请</button><button class="btn" type="button" data-act="autofill" data-id="${j.id}">重新带入资料</button></div><div class="error" id="form-error" role="alert"></div></form>`:`<h3>一次填写，逐份确认</h3><p class="muted" style="margin:10px 0 20px">带入已整理的教育和项目资料，缺失信息会提示补充。填写完成后展示确认页，不会直接提交。</p><button class="btn primary" data-act="autofill" data-id="${j.id}">填写示例信息</button>`}</div></section></div>`;}
function recordsView(){return `<div class="page-head"><div><h1>投递记录</h1><p>记录每次确认与执行结果，避免重复操作。</p></div><button class="btn" data-act="view" data-view="jobs">继续查看岗位</button></div><section class="card">${state.records.length?`<div class="table-wrap"><table><thead><tr><th>岗位</th><th>操作</th><th>状态</th><th>记录详情</th></tr></thead><tbody>${state.records.map(r=>{const j=getJob(state,r.jobId);return `<tr><td><strong>${e(j.company)}</strong><small>${e(j.title)}</small></td><td>${e(r.type)}<small>${e(r.time)}</small></td><td><span class="pill ${r.status==='结果待核验'?'warn':'good'}">${e(r.status)}</span></td><td style="max-width:340px">${e(r.detail)}${r.status==='结果待核验'?`<br><button class="btn link small" data-act="reconcile" data-id="${j.id}">核验示例申请记录</button>`:''}</td></tr>`;}).join('')}</tbody></table></div>`:'<div class="empty"><strong>还没有操作记录</strong>体验一次沟通或网申确认，结果会显示在这里。<div class="actions" style="justify-content:center"><button class="btn primary" data-act="view" data-view="jobs">查看示例岗位</button></div></div>'}</section>`;}
function profileView(){const p=state.profile;return `<div class="page-head"><div><h1>我的资料</h1><p>修改示例资料，观察岗位匹配和打招呼文案如何变化。</p></div><span class="pill neutral">资料版本 v${state.revision}</span></div><section class="card card-pad profile-card"><div class="callout info">资料仅保留在当前页面，刷新后恢复示例。无需输入真实个人信息或上传简历。</div><form id="profile-form"><div class="form-grid">${[['name','称呼'],['school','学校'],['major','专业'],['graduation','毕业年份']].map(([k,label])=>`<label><span class="field-label">${label} *</span><input name="${k}" value="${e(p[k])}" required ${k==='graduation'?'pattern="20[0-9]{2}" maxlength="4"':''}></label>`).join('')}<label><span class="field-label">学历</span><select name="degree">${opt(['本科','硕士','博士'],p.degree)}</select></label><label><span class="field-label">意向城市</span><select name="city">${opt(['上海','北京','杭州'],p.city)}</select></label><label><span class="field-label">每周可到岗天数</span><select name="days">${[1,2,3,4,5].map(v=>`<option value="${v}" ${v===p.days?'selected':''}>${v} 天</option>`).join('')}</select></label><label><span class="field-label">简历文件名称 *</span><input name="resume" value="${e(p.resume)}" required></label><label class="span-2"><span class="field-label">经历与技能 *</span><textarea name="experience" required>${e(p.experience)}</textarea><div class="field-note">例如 PRD、原型、SQL、AI、需求、竞品。演示按关键词展示匹配变化。</div></label></div><div class="actions"><button class="btn primary" type="submit">保存示例资料</button></div><div class="error" id="profile-error" role="alert"></div></form></section>`;}
function render(){const c=counts(state);app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brandmark" aria-hidden="true">↗</span><div><strong>小火箭</strong><small>求职工作台</small></div></div><nav class="nav" aria-label="主导航">${Object.entries(names).map(([k,v])=>`<button data-act="view" data-view="${k}" class="${ui.view===k?'active':''}" ${ui.view===k?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icons[k]}</span>${v}${k==='messages'&&c.pending?`<span class="counter">${c.pending}</span>`:''}</button>`).join('')}</nav><div class="nav-note">产品方案 · 交互演示<br>筛选、检查，再确认。<br><button data-act="reset">重置演示数据</button></div></aside><div class="content"><header class="topbar"><span class="breadcrumb">小火箭 / ${names[ui.view]}</span><div class="top-right"><button class="demo-tag" data-act="about">交互演示 · 非真实投递</button><span class="avatar" aria-hidden="true">${e(state.profile.name.slice(0,1))}</span><span class="profile-name">${e(state.profile.name)}</span></div></header><main id="main" tabindex="-1">${({jobs:jobsView,messages:messagesView,applications:applicationsView,records:recordsView,profile:profileView})[ui.view]()}<footer class="bottom-note"><span>虚构岗位与示例资料 · 不连接招聘平台，不发送消息或提交申请 · 刷新重置</span><button data-act="about">了解演示范围</button></footer></main></div></div>`;}
function modal(title,body,buttons){const active=document.activeElement;modalRoot.innerHTML=`<dialog class="dialog" aria-labelledby="dialog-title"><div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="close" data-close aria-label="关闭">×</button></div><div class="dialog-body">${body}<div class="error" id="dialog-error" role="alert"></div></div><div class="dialog-footer">${buttons}</div></dialog>`;const d=modalRoot.querySelector('dialog');d.showModal();d.addEventListener('close',()=>{modalRoot.innerHTML='';if(active?.isConnected)active.focus();});d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());const check=d.querySelector('#approve-check'),confirm=d.querySelector('#confirm-action');if(check&&confirm){confirm.disabled=true;check.onchange=()=>confirm.disabled=!check.checked;}return {d,confirm};}
function approval(title,body,perform,label='确认并模拟发送'){const {d,confirm}=modal(title,body+'<label class="check"><input id="approve-check" type="checkbox">我已核对本次对象与内容，确认只执行这一次模拟操作。</label>','<button class="btn" data-close>暂不操作</button><button class="btn primary" id="confirm-action">'+label+'</button>');confirm.onclick=()=>{if(confirm.disabled)return;try{perform(d);d.close();render();}catch(error){d.querySelector('#dialog-error').textContent=error.message;}};}
function showAbout(){modal('关于这个 Demo','<div class="demo-help"><p><strong>这是小火箭的产品方案交互演示。</strong>岗位、公司、HR 消息和个人资料均为示例。</p><p>你可以筛选岗位、生成并修改招呼草稿、确认简历请求、填写模拟网申，以及体验断网后的结果核验。</p><p>匹配和文案使用本地预设规则，未接入大模型、BOSS、实习僧或企业官网；所有发送和提交都只更新当前页面的演示记录。关键词规则不能准确理解所有语义，请检查草稿后再确认。</p><p>输入不会上传，刷新即重置。页面没有实际平台登录、文件上传或招聘服务。</p></div>','<button class="btn primary" data-close>开始体验</button>');}
document.addEventListener('input',event=>{
 const input=event.target;
 if(input.id==='greeting'&&state.drafts[ui.selected])state.drafts[ui.selected].text=input.value;
 const form=input.closest('#application-form');
 if(form&&['name','school','major','graduation','experience','email','resume'].includes(input.name))state.forms[form.dataset.id][input.name]=input.value;
});
document.addEventListener('click',event=>{const b=event.target.closest('[data-act]');if(!b||b.disabled)return;const act=b.dataset.act,id=b.dataset.id;try{
 if(act==='view'){ui.view=b.dataset.view;render();document.querySelector('#main').focus({preventScroll:true});}
 else if(act==='pick-job'){ui.selected=id;render();}
 else if(act==='pick-application'){ui.application=id;render();}
 else if(act==='reset-filters'){Object.assign(ui,{q:'',source:'全部平台',city:'全部城市'});render();}
 else if(act==='sync'){const n=syncJobs(state);render();toast(n?'已加入 1 个示例岗位；原岗位没有重复添加':'示例岗位已是最新，没有新增');}
 else if(act==='generate'){generateGreeting(state,id);render();toast('草稿已生成，请检查后再发送');}
 else if(act==='review-greeting'){const text=document.querySelector('#greeting').value.trim(),j=getJob(state,id),revision=state.drafts[id].revision;if(!text)throw Error('请填写打招呼文案');state.drafts[id].text=text;approval('检查这次打招呼',`<p>这次操作只会产生一条模拟沟通记录。</p><dl class="summary"><dt>收件对象</dt><dd>${e(j.company)} · 招聘同事</dd><dt>应聘岗位</dt><dd>${e(j.title)}</dd><dt>发送内容</dt><dd>${e(text)}</dd></dl>`,()=>{sendGreeting(state,id,revision,text);toast('招呼已模拟发送，可继续体验 HR 回复');});}
 else if(act==='reply'){const added=simulateReply(state,id);ui.view='messages';render();toast(added?'收到一条模拟简历请求，等待你的确认':'该岗位已有示例会话，请查看请求');}
 else if(act==='simulate-message'){const j=state.jobs.find(x=>x.source!=='企业官网'&&!state.messages.some(m=>m.jobId===x.id));if(!j){toast('所有示例会话均已添加');return;}simulateReply(state,j.id);render();toast('收到一条模拟简历请求');}
 else if(act==='review-resume'){const m=state.messages.find(x=>x.id===id),j=getJob(state,m.jobId),revision=state.revision,resume=state.profile.resume;approval('确认这次简历发送',`<p>检查公司、岗位与简历版本。这里不会上传或发送真实文件。</p><dl class="summary"><dt>收件对象</dt><dd>${e(j.company)} · 招聘同事</dd><dt>应聘岗位</dt><dd>${e(j.title)}</dd><dt>HR 原话</dt><dd>${e(m.text)}</dd><dt>简历版本</dt><dd>${e(resume)} · 资料 v${revision}</dd><dt>回复内容</dt><dd>您好，这是我的产品方向简历，请查收。</dd></dl>`,()=>{approveResume(state,id,revision,resume);toast('简历已模拟发送，记录已保存');});}
 else if(act==='open-application'){ui.view='applications';ui.application=id;render();}
 else if(act==='autofill'){fillForm(state,id);render();toast('已带入示例资料，请补全邮箱并检查');}
 else if(act==='reconcile'){reconcile(state,id);render();toast('示例记录已核验：提交成功，没有重复提交');}
 else if(act==='about')showAbout();
 else if(act==='reset'){const {d,confirm}=modal('重置演示数据','<p>将清除当前页面里的模拟操作和资料修改，恢复最初的示例。</p>','<button class="btn" data-close>取消</button><button class="btn primary" id="confirm-action">重置演示</button>');confirm.onclick=()=>{state=createState();Object.assign(ui,{view:'jobs',selected:'j1',application:'j4',q:'',source:'全部平台',city:'全部城市'});d.close();render();toast('已恢复示例数据');};}
 }catch(error){toast(error.message);}});
document.addEventListener('submit',event=>{const f=event.target;if(!['filters','profile-form','application-form'].includes(f.id))return;event.preventDefault();try{const values=Object.fromEntries(new FormData(f));if(f.id==='filters'){Object.assign(ui,values);render();}else if(f.id==='profile-form'){updateProfile(state,values);render();toast('资料已保存，旧草稿需要重新生成');}else {const id=f.dataset.id,j=getJob(state,id);state.forms[id]={...values,revision:state.forms[id].revision};validateForm(state.forms[id]);if(state.forms[id].revision!==state.revision)throw Error('资料已更新，请重新带入资料');const snapshot=JSON.stringify(state.forms[id]);const p=state.forms[id];approval('检查本份网申',`<p>只确认当前这一份申请。返回修改后需要重新检查。</p><dl class="summary"><dt>目标公司</dt><dd>${e(j.company)}</dd><dt>应聘岗位</dt><dd>${e(j.title)}</dd><dt>姓名 / 邮箱</dt><dd>${e(p.name)} / ${e(p.email)}</dd><dt>教育经历</dt><dd>${e(p.school)} · ${e(p.major)} · ${e(p.graduation)} 届</dd><dt>相关经历</dt><dd>${e(p.experience)}</dd><dt>简历附件</dt><dd>${e(p.resume)}</dd></dl><label class="check"><input id="network-demo" type="checkbox">体验异常：模拟提交后断网，结果需要核验</label>`,d=>{const unknown=d.querySelector('#network-demo').checked;submitForm(state,id,snapshot,unknown);toast(unknown?'结果待核验，请先检查申请记录':'本份网申已模拟提交');},'确认并模拟提交');}}catch(error){const box=f.querySelector('.error');if(box)box.textContent=error.message;else toast(error.message);}});
render();
// Optional page-scoped WebMCP tools prepare the same visible demo flows; completion remains in the confirmation dialog.
const modelContext=document.modelContext;
if(modelContext?.registerTool){const lifecycle=new AbortController();const specs=[
 {name:'rocket_read_demo_state',title:'读取演示状态',description:'Read the local simulated job and application state. No external systems are connected.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {view:ui.view,counts:counts(state),jobs:state.jobs.map(j=>({id:j.id,title:j.title,source:j.source})),records:state.records};}},
 {name:'rocket_prepare_greeting',title:'准备招呼草稿',description:'Generate a local demonstration greeting and display it for review. Does not send any message.',inputSchema:{type:'object',properties:{jobId:{type:'string'}},required:['jobId'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.jobId!=='string')throw Error('jobId is required');const j=getJob(state,input.jobId);if(j.source==='企业官网')throw Error('Choose a messaging-platform job');generateGreeting(state,j.id);Object.assign(ui,{view:'jobs',selected:j.id,q:'',source:'全部平台',city:'全部城市'});render();return {jobId:j.id,status:'draft_ready',text:state.drafts[j.id].text};}},
 {name:'rocket_open_application',title:'打开模拟网申',description:'Open one simulated company application. Does not fill or submit it.',inputSchema:{type:'object',properties:{jobId:{type:'string'}},required:['jobId'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.jobId!=='string')throw Error('jobId is required');const j=getJob(state,input.jobId);if(j.source!=='企业官网')throw Error('Choose a company-site job');ui.view='applications';ui.application=j.id;render();return {jobId:j.id,status:'application_open'};}}
 ];for(const tool of specs){try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
