export const seedJobs = [
  {id:'j1',company:'星河科技',initial:'星',tone:'blue',title:'AI 产品经理实习生',city:'上海',source:'BOSS直聘',salary:'200–250 元/天',days:4,degree:'硕士',tags:['AI 应用','需求分析','原型设计'],requirements:['2027 届在校生，每周至少到岗 4 天','了解大模型应用，能够整理用户需求','参与 PRD、原型设计和功能验收'],skills:['AI','PRD','原型'],summary:'参与 AI 办公产品的需求整理、原型设计和版本验证，与研发一起改进产品体验。'},
  {id:'j2',company:'泊川软件',initial:'泊',tone:'violet',title:'产品助理实习生',city:'上海',source:'实习僧',salary:'180–220 元/天',days:3,degree:'本科及以上',tags:['企业服务','用户研究','文档'],requirements:['每周至少到岗 3 天，可实习 3 个月','能清晰整理访谈内容和产品需求','熟悉原型工具，做事细致'],skills:['需求','原型'],summary:'协助梳理企业客户的使用问题，整理功能需求，维护产品说明与体验反馈。'},
  {id:'j3',company:'远山互动',initial:'远',tone:'orange',title:'增长产品实习生',city:'北京',source:'BOSS直聘',salary:'220–280 元/天',days:5,degree:'本科及以上',tags:['增长','数据分析','A/B 测试'],requirements:['工作地点北京，每周到岗 5 天','熟悉 SQL 和基础数据分析','对用户增长和实验设计有兴趣'],skills:['SQL','数据'],summary:'参与用户增长活动，分析漏斗数据，协助设计实验并整理结果。'},
  {id:'j4',company:'云帆数据',initial:'云',tone:'teal',title:'数据产品经理 · 秋招',city:'上海',source:'企业官网',salary:'校招岗位',days:0,degree:'硕士',tags:['2027 届','数据产品','官网网申'],requirements:['面向 2027 届毕业生','理解 SQL、数据分析与产品需求','提交教育经历、项目经历和简历附件'],skills:['SQL','需求'],summary:'参与数据工具的规划，整理业务需求，推动数据产品的功能设计。'},
  {id:'j5',company:'木棉科技',initial:'木',tone:'rose',title:'AI 应用产品经理 · 秋招',city:'杭州',source:'企业官网',salary:'校招岗位',days:0,degree:'本科及以上',tags:['2027 届','AI 应用','官网网申'],requirements:['面向 2027 届毕业生','了解 AI 应用场景，能够完成需求文档','具有沟通协作与原型表达能力'],skills:['AI','PRD','原型'],summary:'参与 AI 应用产品规划，从用户反馈中发现问题，并完成方案设计。'},
  {id:'j6',company:'简序信息',initial:'简',tone:'slate',title:'用户研究实习生',city:'上海',source:'BOSS直聘',salary:'180–230 元/天',days:4,degree:'本科及以上',tags:['访谈','竞品分析','体验'],requirements:['每周到岗 4 天及以上','能独立整理资料，表达清楚','有竞品分析或用户访谈经验'],skills:['需求','竞品'],summary:'参与用户访谈与竞品整理，帮助团队理解用户使用过程中的问题。'}
];
export const sampleExtra={id:'j7',company:'澄光软件',initial:'澄',tone:'blue',title:'AI 产品运营实习生',city:'上海',source:'实习僧',salary:'180–220 元/天',days:4,degree:'本科及以上',tags:['AI 工具','用户反馈','内容'],requirements:['每周至少到岗 4 天','了解 AI 工具，善于整理反馈','能够清楚介绍产品功能'],skills:['AI','需求'],summary:'跟进 AI 产品的使用反馈，协助整理需求并维护使用说明。'};
export function createState(){return {revision:1,jobs:structuredClone(seedJobs),profile:{name:'林同学',school:'示例大学',major:'计算数学',degree:'硕士',graduation:'2027',city:'上海',days:4,resume:'产品方向简历_v1.pdf',experience:'参与 AI 产品需求整理、PRD 撰写和原型设计；使用 SQL 分析数据，完成竞品分析。'},drafts:{},statuses:{},forms:{},messages:[{id:'m1',jobId:'j1',text:'你好，看了你的介绍，方便发一份产品方向的简历吗？',intent:'索要简历',status:'pending'}],records:[],synced:false,sequence:2};}
export function getJob(s,id){const job=s.jobs.find(x=>x.id===id);if(!job)throw Error('岗位不存在');return job;}
export function matchJob(s,id){
 const j=getJob(s,id),p=s.profile;
 const positive=p.experience.split(/[；;。！？!?\n]/).filter(t=>!/(没有|未曾|从未|不会|不熟悉|不了解|不具备|暂无|缺乏|尚未|没做过|没学过|不懂|未做过|不擅长|缺少|希望学习|计划学习|正在学习)/.test(t)).join('；');
 const hit=j.skills.filter(k=>positive.toLowerCase().includes(k.toLowerCase())),gaps=[];
 if(j.city!==p.city)gaps.push(`岗位在${j.city}，你的意向城市是${p.city}`);
 if(j.days>p.days)gaps.push(`要求每周 ${j.days} 天，你填写的是 ${p.days} 天`);
 if(j.degree==='硕士'&&p.degree==='本科')gaps.push('岗位要求硕士学历，请确认学历条件');
 const year=j.requirements.join(' ').match(/(20\d{2})\s*届/);
 if(year&&p.graduation!==year[1])gaps.push(`岗位面向 ${year[1]} 届，你填写的是 ${p.graduation} 届`);
 return {hits:hit,gaps,label:gaps.length?'需确认条件':hit.length===j.skills.length?'较匹配':'可进一步了解',level:gaps.length?'warn':'good'};
}
export function generateGreeting(s,id){const j=getJob(s,id),p=s.profile;const m=matchJob(s,id);const evidence=m.hits.length?`我的经历涉及${m.hits.join('、')}。`:'我希望进一步了解岗位的具体工作。';const text=`您好，我是${p.name}，${p.graduation}届${p.degree}，关注贵公司的${j.title}岗位。${evidence}${j.days?`目前每周可到岗${p.days}天。`:''}方便进一步沟通吗？`;s.drafts[id]={text,revision:s.revision};return text;}
export function updateProfile(s,p){const clean={...p};for(const k of ['name','school','major','degree','graduation','city','resume','experience']){if(typeof clean[k]!=='string'||!clean[k].trim())throw Error('请补全资料');clean[k]=clean[k].trim();}clean.days=Number(clean.days);if(!Number.isInteger(clean.days)||clean.days<1||clean.days>5)throw Error('到岗天数须为 1–5 天');if(!/^20\d{2}$/.test(clean.graduation))throw Error('请填写四位毕业年份');s.profile=clean;s.revision++;}
export function addRecord(s,jobId,type,status,detail){const rec={id:`r${s.sequence++}`,jobId,type,status,detail,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})};s.records.unshift(rec);return rec;}
export function sendGreeting(s,id,revision,text){getJob(s,id);if(revision!==s.revision)throw Error('资料已变更，请重新生成并确认文案');if(s.statuses[id]?.greeting)throw Error('这个岗位已经模拟沟通过了');if(typeof text!=='string'||!text.trim()||text.length>500)throw Error('请填写 1–500 字的文案');s.statuses[id]={...s.statuses[id],greeting:true};addRecord(s,id,'打招呼','已模拟发送',text);}
export function simulateReply(s,id){getJob(s,id);if(s.messages.some(m=>m.jobId===id))return false;s.messages.unshift({id:`m${s.sequence++}`,jobId:id,text:'你好，方便发一份简历吗？我们想了解你的项目经历。',intent:'索要简历',status:'pending'});return true;}
export function approveResume(s,messageId,revision,resume){const m=s.messages.find(x=>x.id===messageId);if(!m||m.status!=='pending')throw Error('该请求已处理或不存在');if(revision!==s.revision||resume!==s.profile.resume)throw Error('简历版本已变更，请重新确认');m.status='sent';addRecord(s,m.jobId,'发送简历','已模拟发送',resume);}
export function fillForm(s,id){const j=getJob(s,id);if(j.source!=='企业官网')throw Error('请选择官网岗位');if(s.statuses[id]?.application)throw Error('该岗位已有申请记录，请到投递记录核对');const p=s.profile;s.forms[id]={name:p.name,school:p.school,major:p.major,graduation:p.graduation,experience:p.experience,email:'',resume:p.resume,revision:s.revision};return s.forms[id];}
export function validateForm(form){if(!form)throw Error('请先填写网申');for(const k of ['name','school','major','graduation','experience','email','resume'])if(!String(form[k]||'').trim())throw Error('请补全所有必填项');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))throw Error('请填写有效邮箱');if(!/^20\d{2}$/.test(String(form.graduation)))throw Error('请填写四位毕业年份');}
export function submitForm(s,id,approvedSnapshot,unknown=false){const f=s.forms[id];validateForm(f);if(s.statuses[id]?.application)throw Error('已有申请记录，不能重复提交');if(f.revision!==s.revision||JSON.stringify(f)!==approvedSnapshot)throw Error('资料或填写内容已变更，请重新检查');const status=unknown?'结果待核验':'已模拟提交';s.statuses[id]={...s.statuses[id],application:status};addRecord(s,id,'官网网申',status,unknown?'演示场景：提交后网络断开，暂不重复提交。':`已提交示例表单 · ${f.resume}`);}
export function reconcile(s,id){if(s.statuses[id]?.application!=='结果待核验')throw Error('无需核验');s.statuses[id].application='已模拟提交';const r=s.records.find(x=>x.jobId===id&&x.status==='结果待核验');r.status='已模拟提交';r.detail='已核对示例申请记录，确认本次提交成功；没有重复提交。';}
export function syncJobs(s){if(s.synced)return 0;s.jobs.push(structuredClone(sampleExtra));s.synced=true;return 1;}
export function counts(s){return {jobs:s.jobs.length,pending:s.messages.filter(m=>m.status==='pending').length,applications:Object.values(s.statuses).filter(x=>x.application==='已模拟提交').length,unknown:s.records.filter(x=>x.status==='结果待核验').length};}
