import * as Base from './engine.mjs';
export const {getJob,matchJob,generateGreeting,sendGreeting,validateForm:validateLegacy}=Base;
const meta={j1:['徐汇区','B 轮','150–500 人','人工智能','周祺','招聘经理'],j2:['杨浦区','A 轮','50–150 人','企业服务','陈宁','人才招聘'],j3:['朝阳区','C 轮','500–1000 人','互联网','林越','HRBP'],j4:['浦东新区','C 轮','500–1000 人','数据服务','招聘团队','校园招聘'],j5:['余杭区','B 轮','150–500 人','人工智能','招聘团队','校园招聘'],j6:['静安区','A 轮','50–150 人','效率工具','叶清','招聘同事'],j8:['滨江区','A 轮','50–150 人','内容工具','许知','人才招聘'],j9:['杨浦区','B 轮','150–500 人','企业服务','招聘团队','校园招聘']};
function enrich(j){const [district,stage,size,industry,hr,hrRole]=meta[j.id]||meta.j2;return {...j,district,stage,size,industry,hr,hrRole,posted:['j1','j2','j4','j8'].includes(j.id)?'今天':'昨天',salary:j.days?j.salary.replace(' 元/天',''):j.id==='j5'?'20–30K':'18–25K',unit:j.days?'元/天':'· 14 薪',duties:['整理用户反馈，明确产品需求与优先级','参与产品原型、需求文档及功能验收','与团队协作，跟进产品体验与版本迭代']};}
export function createState(){const s=Base.createState();s.schema=2;s.jobs=s.jobs.map(enrich);s.jobs.push(enrich({...Base.seedJobs[1],id:'j8',company:'流光创作',initial:'流',title:'AIGC 产品运营实习生',city:'杭州',skills:['AI','需求'],tags:['AIGC','内容创作','用户运营'],summary:'和创作者一起打磨 AI 内容工具，探索新技术在创作流程中的实际价值。'}));s.jobs.push(enrich({...Base.seedJobs[3],id:'j9',company:'知合网络',initial:'知',title:'产品经理 · 秋招',degree:'本科及以上',tags:['2027 秋招','企业服务','需求分析']}));s.profile.email='';s.saved=['j1','j4'];s.resumes=[{name:'产品方向简历_v1.pdf',direction:'产品岗位',note:'需求分析、PRD 与原型设计'},{name:'数据方向简历_v1.pdf',direction:'数据岗位',note:'SQL、数据分析与业务理解'}];s.messages[0]={...s.messages[0],unread:true,thread:[{side:'system',text:'以下为示例会话',time:'09:40'},{side:'hr',text:'你好，看了你的项目介绍，和我们在做的 AI 办公方向比较匹配。方便发一份产品方向的简历吗？',time:'09:41'}]};s.messages.push({id:'m2',jobId:'j2',status:'conversation',unread:false,text:'岗位每周至少到岗 3 天，你目前的时间安排方便吗？',thread:[{side:'system',text:'以下为示例会话',time:'昨天'},{side:'hr',text:'你好，欢迎关注泊川。岗位每周至少到岗 3 天，你目前的时间安排方便吗？',time:'16:20'}]});s.sequence=3;s.scenario={network:false,reconcileMissing:false};return s;}
export function updateProfile(s,p){const email=String(p.email||'').trim();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('邮箱格式不正确');Base.updateProfile(s,{...p,email});}
export function chooseResume(s,name){if(!s.resumes.some(r=>r.name===name))throw Error('简历版本不存在');if(s.profile.resume!==name){s.profile.resume=name;s.revision++;}}
export function getConversation(s,id){return s.messages.find(m=>m.jobId===id);}
function thread(s,id){let m=getConversation(s,id);if(!m){m={id:`m${s.sequence++}`,jobId:id,status:'conversation',unread:false,text:'',thread:[]};s.messages.unshift(m);}return m;}
function append(m,entry){m.thread.push({...entry,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});m.text=entry.text||entry.file;}
function stamp(s,resume=s.profile.resume){const r=s.records[0];r.at=new Date().toISOString();r.resume=resume;}
export function greet(s,id,revision,text){Base.sendGreeting(s,id,revision,text);append(thread(s,id),{side:'me',text});stamp(s);}
export function sendChat(s,messageId,text,revision){const m=s.messages.find(x=>x.id===messageId);if(!m)throw Error('会话不存在');if(revision!==s.revision)throw Error('资料已更新，请重新检查消息');if(!text.trim()||text.length>1000)throw Error('消息须为 1–1000 字');append(m,{side:'me',text});s.statuses[m.jobId]={...s.statuses[m.jobId],greeting:true};Base.addRecord(s,m.jobId,'会话消息','已模拟发送',text);stamp(s);}
export function simulateReply(s,id){const m=thread(s,id);if(m.status==='pending'||m.status==='sent')return false;m.status='pending';m.unread=true;append(m,{side:'hr',text:'谢谢你的介绍，方便发一份简历吗？我们想进一步了解你的项目经历。'});return true;}
export function approveResume(s,messageId,revision,resume){Base.approveResume(s,messageId,revision,resume);const m=s.messages.find(x=>x.id===messageId);m.unread=false;s.statuses[m.jobId]={...s.statuses[m.jobId],greeting:true};append(m,{side:'me',file:resume,text:'您好，这是我的简历，请查收。',profile:structuredClone(s.profile)});stamp(s);}
export function fillForm(s,id){const f=Base.fillForm(s,id);f.email=s.profile.email||'';f.degree=s.profile.degree;f.step=0;return f;}
export function validateForm(f,step=null){if(!f)throw Error('请先带入简历资料');const groups=[['name','email'],['school','major','degree','graduation'],['experience'],['resume']],keys=step===null?groups.flat():groups[step];if(keys.some(k=>!String(f[k]||'').trim()))throw Error('请补全本页的必填项');if((step===null||step===0)&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email))throw Error('请填写有效邮箱，例如 lin.demo@example.com');if((step===null||step===1)&&!/^20\d{2}$/.test(String(f.graduation)))throw Error('请填写四位毕业年份');}
export function submitForm(s,id,snapshot,unknown=false){validateForm(s.forms[id]);Base.submitForm(s,id,snapshot,unknown);stamp(s,s.forms[id].resume);if(unknown)s.scenario.network=false;}
export function reconcile(s,id,missing=false){if(!missing){Base.reconcile(s,id);return;}if(s.statuses[id]?.application!=='结果待核验')throw Error('当前申请无需核验');const r=s.records.find(x=>x.jobId===id&&x.status==='结果待核验');if(!r)throw Error('申请记录不存在');delete s.statuses[id].application;r.status='已核验未提交';r.detail='示例核验结果：没有查到申请记录，可重新检查后提交。';}
export function syncJobs(s){const n=Base.syncJobs(s);if(n)s.jobs[s.jobs.length-1]=enrich(s.jobs.at(-1));return n;}
export function counts(s){return {...Base.counts(s),saved:s.saved.length,unread:s.messages.filter(m=>m.unread).length,greetings:Object.values(s.statuses).filter(x=>x.greeting).length};}
export function restoreState(raw){try{const s=JSON.parse(raw);if(s.schema!==2||!Number.isInteger(s.revision)||!s.profile||!Array.isArray(s.jobs)||!Array.isArray(s.messages)||!Array.isArray(s.records)||!Array.isArray(s.saved)||!Array.isArray(s.resumes)||!s.forms||!s.drafts||!s.statuses||!s.scenario)throw Error();const allowed=new Set(['j1','j2','j3','j4','j5','j6','j7','j8','j9']);if(s.jobs.some(j=>!allowed.has(j.id))||s.messages.some(m=>!allowed.has(m.jobId)||!Array.isArray(m.thread))||s.records.some(r=>!allowed.has(r.jobId)))throw Error();if(new Set(s.messages.map(m=>m.id)).size!==s.messages.length||typeof s.profile.name!=='string'||typeof s.profile.experience!=='string')throw Error();return s;}catch{return createState();}}
